image: golang:1.9-alpine

variables:
  DOCKER_DRIVER: overlay
  PKG_PATH: github.com/jetstack/cert-manager

services:
- docker:1.12-dind

before_script:
  - apk --update add make docker bash curl git gcc
  - export DOCKER_HOST=${DOCKER_PORT}
  - docker info > /dev/null
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - mkdir -p "${GOPATH}/src/${PKG_PATH}" && rmdir "${GOPATH}/src/${PKG_PATH}"
  - mv "${CI_PROJECT_DIR}" "${GOPATH}/src/${PKG_PATH}"
  - cd "${GOPATH}/src/${PKG_PATH}"
  - mkdir -p "${CI_PROJECT_DIR}"

after_script:
  - cd "/"
  - rm -rf "${CI_PROJECT_DIR}"
  - mv "${GOPATH}/src/${PKG_PATH}" "${CI_PROJECT_DIR}"

build:
  tags:
  - docker
  script:
  - make verify push IMAGE_TAGS="${CI_BUILD_REF_NAME}"
  except:
  - tags

