apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cert-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cert-manager
    spec:
      containers:
      - name: cert-manager
        image: quay.io/jetstack/cert-manager-controller:v0.2.2
        imagePullPolicy: Always
      - name: ingress-shim
        image: quay.io/jetstack/cert-manager-ingress-shim:v0.2.2
        imagePullPolicy: Always
