apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: boulder
  name: boulder
spec:
  ports:
  - name: "4000"
    port: 4000
    targetPort: 4000
  - name: "4001"
    port: 4001
    targetPort: 4001
  - name: "4002"
    port: 4002
    targetPort: 4002
  - name: "4003"
    port: 4003
    targetPort: 4003
  - name: "4430"
    port: 4430
    targetPort: 4430
  - name: "4431"
    port: 4431
    targetPort: 4431
  - name: "4500"
    port: 4500
    targetPort: 4500
  - name: "6000"
    port: 6000
    targetPort: 6000
  - name: "8000"
    port: 8000
    targetPort: 8000
  - name: "8001"
    port: 8001
    targetPort: 8001
  - name: "8002"
    port: 8002
    targetPort: 8002
  - name: "8003"
    port: 8003
    targetPort: 8003
  - name: "8004"
    port: 8004
    targetPort: 8004
  - name: "8005"
    port: 8005
    targetPort: 8005
  - name: "8006"
    port: 8006
    targetPort: 8006
  - name: "8008"
    port: 8008
    targetPort: 8008
  - name: "8009"
    port: 8009
    targetPort: 8009
  - name: "8010"
    port: 8010
    targetPort: 8010
  - name: "8055"
    port: 8055
    targetPort: 8055
  - name: "9380"
    port: 9380
    targetPort: 9380
  - name: "9381"
    port: 9381
    targetPort: 9381
  selector:
    io.kompose.service: boulder
status:
  loadBalancer: {}
