# Default values for cert-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: quay.io/jetstack/cert-manager-controller
  tag: v0.2.2
  pullPolicy: Always

createCustomResource: true

rbac:
  enabled: true

resources:
  requests:
    cpu: 10m
    memory: 32Mi

ingressShim:
  enabled: true
  # Optional additional arguments for ingress-shim
  extraArgs: []
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
  image:
    repository: quay.io/jetstack/cert-manager-ingress-shim
    # Defaults to image.tag.
    # You should only change this if you know what you are doing!
    # tag: v0.2.2
    pullPolicy: Always
